#-------------------------------------------------
#    File: dashboard/Dockerfile
#    Type: Dockerfile
#    Project: driveway-organizer
#    Author: urban
#    Created: 2024-06-20
#
#    Description: Dockerfile for dashboard service
#
#    Version --  Date  -- Author
#    1.0      2024-06-20  Kurban  
#-------------------------------------------------

FROM nginx:stable-alpine

COPY . /usr/share/nginx/html

EXPOSE 80
